apiVersion: v1
kind: Service
metadata:
  name: nutrition-web
  namespace: nutrition-web
  labels:
    app: nutrition-web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: nutrition-web
