apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-pgvector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea_admin:twhljpF7zDnBzNuEQb4J@gitea-internal.code.svc.cluster.local:3000/gitea_admin/devops
    targetRevision: dev
    path: k8s/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /metadata/labels/argocd.argoproj.io~1instance
  syncPolicy: {}
