apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deepdive
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://gitea-internal:3000/gitea_admin/devops.git # Internal URL from your cluster to fetch from Gitea
    targetRevision: HEAD
    path: deepdive/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: deepdive
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
