apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deepdive
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://gitea_admin:twhljpF7zDnBzNuEQb4J@gitea-internal.code.svc.cluster.local:3000/gitea_admin/devops.git
    targetRevision: dev
    path: deepdive/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: deepdive
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
