apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
  namespace: code # Deploying to same namespace as PG for simplicity
type: Opaque
stringData:
  # This should match the credentials created in PG cluster
  username: "gitea_admin"
  password: "twhljpF7zDnBzNuEQb4J" 
