apiVersion: v1
kind: Secret
metadata:
  name: gitea-db-secret
  namespace: code # Deploying to same namespace as PG for simplicity
type: Opaque
stringData:
  # This should match the credentials created in PG cluster
  DB_TYPE: "postgres"
  DB_HOST: "postgresql-cluster-rw.database.svc.cluster.local:5432"
  DB_NAME: "app_db"
  DB_USER: "app_user"
  DB_PASSWD: "ZGB9M1E9IJUS3NNcwtMs" # Match the password in postgresql-app-user-creds
