apiVersion: batch/v1
kind: Job
metadata:
  name: pubmed-ingestor-job
  namespace: deepdive
  labels:
    app: deepdive
    component: pubmed-ingestor
spec:
  template:
    metadata:
      labels:
        app: deepdive
        component: pubmed-ingestor
    spec:
      containers:
        - name: ingestor
          image: localhost:32000/llm/ingestion/pubmed-ingestor:0.1.2
          envFrom:
            - configMapRef:
                name: pubmed-ingestor-config
          env:
            - name: SSL_CERT
              value: "/etc/client-certs/client.crt"
            - name: SSL_KEY
              value: "/etc/client-certs/client.key"
            - name: SSL_CA
              value: "/etc/client-certs/ca.crt"
          volumeMounts:
            - name: data-volume
              mountPath: /opt/llm-data-pretraining/data
            - name: client-certs
              mountPath: /etc/client-certs
              readOnly: true
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 1000
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: llm-data-pvc
        - name: client-certs
          secret:
            secretName: deepdive-tls-certs
            items:
              - key: client.crt
                path: client.crt
              - key: client.key
                path: client.key
              - key: ca.crt
                path: ca.crt
  backoffLimit: 4
